site_name: Bioinformatics - An Interactive Course
repo_url: https://github.com/dmccreary/bioinformatics
site_url: https://dmccreary.github.io/bioinformatics/
site_description: An interactive intelligent textbook for Bioinformatics with a focus on graph analysis.
site_author: Dan McCreary

nav:
  - Home: index.md
  - Course Description: course-description.md
  - License: license.md
  - Contact: contact.md

theme:
  name: material
  # logo: img/logo.png
  # favicon: img/favicon.ico
  palette:
    primary: 'green'
    accent: 'white'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit

plugins:
  - search
  - social
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  - js/mathjax-config.js
  - https://unpkg.com/mathjax@3/es5/tex-chtml.js

# Watch these files for changes to trigger a rebuild
watch:
  - docs
  - mkdocs.yml

copyright: Copyright &copy; 2026 Dan McCreary. Licensed under <a href="license/">CC BY-NC-SA 4.0</a> for non-commercial use.

extra:
  # remove the made with mkdocs from the footer
  generator: false
  #analytics:
  #  provider: google
  #  property: G-XXXXXXXXXX
  schema: https://dmccreary.github.io/intelligent-textbooks/ns/textbook/v1
  textbook_name: Bioinformatics
  textbook_version: "1.0"